# Generated by Django 2.0.3 on 2018-04-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('api', '0001_initial'), ('api', '0002_task_task_completed'), ('api', '0003_auto_20180410_2121'), ('api', '0004_auto_20180412_1716'), ('api', '0005_auto_20180413_2040')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=50)),
                ('task_completed', models.BooleanField(default='False')),
                ('task_maxstreak', models.IntegerField(default=0)),
                ('task_streak', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CompletionDate',
            fields=[
                ('completion_date', models.DateField(auto_now_add=True, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='completion_dates',
            field=models.ManyToManyField(to='api.CompletionDate'),
        ),
    ]
