# Generated by Django 2.0.3 on 2018-04-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('api', '0001_initial')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=50)),
            ],
        ),
    ]
