# Generated by Django 2.0.3 on 2018-05-29 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from accounts.models import UserProfile
from django.contrib.auth.models import User


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    def create_user_profile(apps, schema_editoR):
        for user in User.objects.all():
            UserProfile.objects.get_or_create(user=user)

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('vacation', models.BooleanField(default=False)),
            ],
        ),
        migrations.RunPython(create_user_profile),
    ]
