version: '3'

services:
  django-wsgi:
    build:
      context: ./
      dockerfile: ./conf/django/Dockerfile
    env_file: ./conf/production-env.env
    volumes:
        - "dailio-static:/var/www/static"
        - "dailio-db:/var/www/dailio/db"

  nginx-proxy:
    build:
      context: ./conf/nginx
    ports:
      - 80:80
    volumes:
      - "dailio-static:/var/www/static"
    depends_on:
      - django-wsgi

volumes:
  dailio-static:
  dailio-db:
